# Generated by Django 3.2.9 on 2021-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followcompany',
            name='receive_email',
        ),
        migrations.RemoveField(
            model_name='followcompany',
            name='receive_sms',
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('destinations', models.ManyToManyField(related_name='alarms', to='news.FollowCompany')),
            ],
        ),
    ]
