# Generated by Django 3.2.9 on 2021-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211115_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='destinations',
            field=models.ManyToManyField(default=False, related_name='alarms', to='news.FollowCompany'),
        ),
    ]
