# Generated by Django 3.2.9 on 2021-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_alarm_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='destinations',
            field=models.ManyToManyField(related_name='alarms', to='news.FollowCompany'),
        ),
    ]
